language: ruby
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-head-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  # Please add to Rakefile instead of this section.
  - bundle exec rspec
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
