language: ruby
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-head-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  # Please add to Rakefile instead of this section.
  - bundle exec rspec
  # If travis is setup to build PR only, uncomment the line below
  # - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  # If travis is setup to build PR only, comment the line below
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
env:
  global:
    - CC_TEST_REPORTER_ID=ab37414fb95f728c38c29e3c9a95abff82ed9c39447b70a89e520b93b2d1fa83
