language: ruby
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  # Please add to Rakefile instead of this section.
  - bundle exec rspec
after_script:
  # Confirm cce instance hostname
  - cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  # TODO update for repo token
  - CODECLIMATE_REPO_TOKEN=ab37414fb95f728c38c29e3c9a95abff82ed9c39447b70a89e520b93b2d1fa83
