language: ruby
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-git-env-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  # Please add to Rakefile instead of this section.
  - bundle exec rspec
after_script:
  # Confirm cce instance hostname
  - echo $GIT_COMMIT_SHA
  - echo $GIT_COMMITTED_AT
  - echo $GIT_BRANCH
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug
env:
  # TODO update for repo token
  global:
    - CC_TEST_REPORTER_ID=ab37414fb95f728c38c29e3c9a95abff82ed9c39447b70a89e520b93b2d1fa83
    - GIT_COMMIT_SHA=$(git rev-parse --verify HEAD)
    - GIT_COMMITTED_AT=$(git log -1 --pretty=format:%ct)
    - GIT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
